### ISSUE TITLE
^1

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#23]
I noticed one little issue while proofing the chapters: Prof. Imamoglu uses the American version to write a "1" which looks like a "|". So if she writes R^' (R as in \R), she actually means R^1; the same also applies for the functions of class C^1 (once-differentiable), it's not C^' but C^1. I noticed this mistake several times but unfortunately my TeX isn't very good... If you find the time, could you either put a notice at the beginning or fix it? Thanks!

**Comment by limenet** [comment]
E.g. Def 8.8

**Comment by limenet** [comment]
and of course this does _not_ apply to f^' (as in first derivative)

**Comment by pennatil** [comment]
I'm gonna let Prof. Imamoglu track down the mistakes, so to avoid doing the same work twice!
