### ISSUE TITLE
Scripts will fail when not called from within the script directory

### ISSUE THREAD

**Issue by ghost** [pennatil/Analysis-Notes#38]
Not really a huge issue, but I might fix that at some point.

**Comment by pennatil** [comment]
Maybe a make file could solve this?

**Comment by bimmlerd** [comment]
I think a Makefile would probably be a bit of an overkill, it should be possible in bash :)

**Comment by pennatil** [comment]
You might be right, but something along the lines of what you can find [here](https://github.com/MartinThoma/LaTeX-examples) could be easy enough to do

**Comment by bimmlerd** [comment]
:+1: go ahead, I don't have much experience with Makefiles :)

**Comment by pennatil** [comment]
nevermind, just did some research and they need the absolute path...same problem as bash

**Comment by bimmlerd** [comment]
I guess we should at least let it fail loudly, because as it stands it will delete some files in your current directory if you don't call it from within Scripts^^

did that in 00baed7a18675613800c0710b6f6eefe03333c94

**Comment by pennatil** [comment]
Ok, sounds good to me!
