### ISSUE TITLE
BuildAll.sh under Windows

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#39]
@bimmlerd I used to be able to run BuildAll.sh on Windows without any errors (surprisingly). When running it in cmd, it looks like it uses my git installation to do so (otherwise stuff like `cd` wouldn't work).
Yet after you introduced 00baed7a18675613800c0710b6f6eefe03333c94 the script doesn't run anymore and doesn't output an error messages either.
Yes, I know Windows isn't supported officially (and I don't blame you for it at all) and I understand the need for safe scripts. But still, it would be nice, wouldn't it? After all it used to work... ;)

---

Output before 00baed7a18675613800c0710b6f6eefe03333c94

```
F:\Users\Linus\Documents\Web\Projects\_GitHub\Analysis-Notes\Scripts>BuildAll.sh
Welcome to Git (version 1.8.5.2-preview20131230)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/W32TeX)
 \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2011/06/27>
Babel <3.9k> and hyphenation patterns for 78 languages loaded.

[.............]

Output written on main.pdf (251 pages, 1086839 bytes).
SyncTeX written on main.synctex.
Transcript written on main.log.
F:\Users\Linus\Documents\Web\Projects\_GitHub\Analysis-Notes\Scripts\BuildAll.sh: line 18: growlnotify: command not found


#### FINISHED GENERATING MAIN, CAN BE FOUND IN THE PDF FOLDER ####
```

Output after 00baed7a18675613800c0710b6f6eefe03333c94

```
F:\Users\Linus\Documents\Web\Projects\_GitHub\Analysis-Notes\Scripts>BuildAll.sh
Welcome to Git (version 1.8.5.2-preview20131230)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
```

**Comment by pennatil** [comment]
Already have a fix in the pipeline, give 5 mins and it is pushed. @bimmlerd just FIY

**Comment by pennatil** [comment]
Fixed in commit 9792b15afb3d5bfb757c93d774670a662d936ae2. Let me know if it works!

**Comment by bimmlerd** [comment]
@limenet `cd` is valid in cmd too:) but yeah, of course it should work in win too :+1: 
@pennatil ahh yep that might well be the issue, quick thinking!

**Comment by pennatil** [comment]
although quite ridiculous, that solved it

**Comment by limenet** [comment]
@pennatil works like a charm, thanks!
@bimmlerd yep,you're right, `ls` is the one that doesn't work, my bad ;)
