### ISSUE TITLE
Better geometry with the geometry package

### ISSUE THREAD

**Issue by bimmlerd** [pennatil/Analysis-Notes#42]
I just pushed a branch BetterGeometry (30be02240f357b10f634e6b97503b94298bf383f) with (imho) better geometry, using the geometry package. It looks better and is more readable, but some of the todo comments become cut off at the sides. I leave the decision to @pennatil whether this will be merged now, merged when we don't need the todos anymore or not merged at all.

**Comment by pennatil** [comment]
Sounds good to me, I'll take a look at it once I'm home, and then we just keep it in sync with the main branch and then decide at the end

**Comment by bimmlerd** [comment]
I also added `\linespread{1.1}` since in some cases in chapter 3 there were some issues with sequences like ![image](https://cloud.githubusercontent.com/assets/7094770/3492577/6bf48668-05ac-11e4-8694-04318ea455cd.png) and a line of text directly below, as high chars from below would touch the `\geq`.

**Comment by pennatil** [comment]
I took a look at the layout, and it looks good, but I think this is better if for example, you print two pages onto one, as it uses the space better...If you are printing it one page per page, the normal book class looks better to me, but we can keep them in sync and then release both version, not a problem

**Comment by bimmlerd** [comment]
:+1:
