### ISSUE TITLE
Issues with References within the Document

### ISSUE THREAD

**Issue by bimmlerd** [pennatil/Analysis-Notes#43]
At the moment, it's really hard to reference a specific part of the document, like wanting to reference Korollar 2.11 from Example 3.14, because most of the section numbers are hardcoded for compatability with the handwritten notes. This means that `\label` and subsequent `\ref`s will display a most likely wrong section number.
This could be improved by attempting to work with the counters, but I think this will be quite difficult.
Does anybody have an idea how to improve this?

**Comment by pennatil** [comment]
I would avoid working with automatic counters as this would completely throw off the ordering that exists now, not to mention many hours more of work. For referencing pages, I have been going with the method that if it is not in the same document, you just don't reference it. What you could do is hardcode the reference, i.e. just write "See korollar 2.15", without specifying a page. Although not at all elegant, it should work

**Comment by bimmlerd** [comment]
Alright, we'll won't-fix this ;)
