### ISSUE TITLE
Picture for Mitterlwertsatz der Integration

### ISSUE THREAD

**Issue by bimmlerd** [pennatil/Analysis-Notes#45]
The point of the picture on p. 136 in the complete file would sort of be to show that A+B = C + D
![screen shot 2014-07-12 at 16 41 50](https://cloud.githubusercontent.com/assets/7094770/3561770/e9e7b336-09d2-11e4-8474-0026cb82ebf0.png)

But in your's it doesn't reeeallly look that way :grin: 
![screen shot 2014-07-12 at 16 44 06](https://cloud.githubusercontent.com/assets/7094770/3561774/005d628c-09d3-11e4-9896-f8917ace335a.png)

And I can't handle the tikz magic, I'm afraid.

**Comment by pennatil** [comment]
oh s**t...I never noticed...I'll take care of it once I get home!

**Comment by pennatil** [comment]
Fixed in commit 7a86f06cd3b76331a2b979684a704de6a292f7cb of branch drawingChange. Take a look and let me know!

**Comment by bimmlerd** [comment]
Yeah, looks a lot better, thanks!

**Comment by pennatil** [comment]
Ok, merged
