### ISSUE TITLE
Chapter 2, Page II–2, II–3

### ISSUE THREAD

**Issue by zenoli** [pennatil/Analysis-Notes#47]
"Folgerung 2.3" is labeled "i-ix" whereas "Beweis 2.3" is "a-f"

(don't know if on purpose, but a little confusing when scrolling through...)

**Comment by pennatil** [comment]
Not on purpose...give me 5 mins and it is fixed

**Comment by pennatil** [comment]
Fixed in commit d88f7d2c7c87ec47a69207a36a3cc5bb87f53766, Thanks!

**Comment by zenoli** [comment]
That was fast ;-)
