### ISSUE TITLE
Chapter 1: Title

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#62]
I don't know about you, but I think the title of the first chapter should be "Logik und Grundlagen" instead of "Logik und Unterlagen". I'm sure this was a poor choice of words and "Grundlagen" just makes more sense (to me).

**Comment by pennatil** [comment]
To be honest, I have no control over this...It's up to Imamoglu really. But if you think it's better, I have no problem with changing it. @bimmlerd What do you think?

**Comment by bimmlerd** [comment]
Absolutely. I've been thinking of changing this for a while now, just never had the guts xD

**Comment by pennatil** [comment]
haha ok then, I'll change it

**Comment by limenet** [comment]
Tthis is just great!
