### ISSUE TITLE
Chapter 4: R^n

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#63]
In Chapter_4.tex on line 201 it says

``` tex
von $\Omega\subseteq\R^{d}$ nach $\R{n}$
```

while it should be (missing ^ for R^n)

``` tex
von $\Omega\subseteq\R^{d}$ nach $\R^{n}$
```

**Comment by bimmlerd** [comment]
For such small changes, you can usually do it online within github, just go to the file in question and select 'edit', it'll do what's necessary and even submit a PR :)

**Comment by limenet** [comment]
You're right, totally forgot about that feature... Thanks!

**Comment by bimmlerd** [comment]
Yeah no problem, I can do it just as fast ;)
And since they just changed the layout, it's not edit anymore, but the pen^^

**Comment by limenet** [comment]
Just tried it out in #66 ;)
Yep, and I think it looks even slicker now ^^
