### ISSUE TITLE
Chapter 4: epsilon-delta criterion

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#64]
Chapter_4.tex Line 376 reads 

``` tex
\[ \forall\varepsilon>0\;\exists\delta>0: \forall x\in\Omega,\norm{x-x_{0}}<\delta \implies \norm{\delta(x)-\delta(x_{0})}<\varepsilon\]
```

while it should be (yes, Prof's handwriting might be confusing)

``` tex
\[ \forall\varepsilon>0\;\exists\delta>0: \forall x\in\Omega,\norm{x-x_{0}}<\delta \implies \norm{\f(x)-\f(x_{0})}<\varepsilon\]
```

Explanation: delta is a number, f is a function. If you check [Wikipedia](https://en.wikipedia.org/wiki/%28%CE%B5,_%CE%B4%29-definition_of_limit) and [Mathworld by Wolfram](http://mathworld.wolfram.com/Epsilon-DeltaDefinition.html) you get a slightly different definition, but they all boil down to f(x)-f(x_0). And on the review on page 16 it's also like this (in a more legible form).

I hope I'm not wrong ;)

**Comment by bimmlerd** [comment]
Thanks :)

**Comment by bimmlerd** [comment]
Ergh, I botched that one up
Should be

``` tex
\[ \forall\varepsilon>0\;\exists\delta>0: \forall x\in\Omega,\norm{x-x_{0}}<\delta \implies \norm{f(x)-f(x_{0})}<\varepsilon\]
```

(no backslash before f) and I also failed at pasting it in xD
Fixed now.

**Comment by limenet** [comment]
Thanks :)
