### ISSUE TITLE
Chapter 5: Missing Sections

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#65]
I just noticed the sections on Taylor series and local minima/maxima are missing in chapter 5 -- and the corresponding PDFs aren't in the repo either. [Week 13](https://www.dropbox.com/s/m5bxvf5lci2a4im/Analysis-INFK-week13.pdf), [Week 14](https://www.dropbox.com/s/9wp35k00jfftxhn/Analysis-INFK-week14.pdf)

**Comment by bimmlerd** [comment]
Ouch, that's a big one. :+1: for noticing, thanks!
Currently do not have too much time on my hands, @pennatil can you cope with adding the two sections?

**Comment by bimmlerd** [comment]
Added missing source material in 81b764dc503e0c4cb630728ff9c22bf9e9250381

**Comment by limenet** [comment]
You're welcome! :)

**Comment by pennatil** [comment]
I'm in the same boat as you, don't really have the time right now. @limenet thanks for noticing, don't know how it slipped past me. Anyways I'll try to see if I have time on the weekend, otherwise it slips to after the exams

**Comment by pennatil** [comment]
I just added a chapter5 branch, with the first part of the addition. When youhave 5 mins please take a look at it

**Comment by limenet** [comment]
Thanks! Sure, I just hunted a few typos down, see #72

**Comment by pennatil** [comment]
Merged, thanks for the corrections. I should have another big chunk by tonight

**Comment by limenet** [comment]
You're welcome. You were awfully fast merging :flushed: 
I'll have a look at it.

**Comment by pennatil** [comment]
Done with the content. Only missing a drawing, should be able to add it this weekend.

**Comment by limenet** [comment]
Thanks for the work, @pennatil ! See #73 for some corrections.

**Comment by pennatil** [comment]
Merged, thanks for your help. @bimmlerd can you take a look at some of the layout issues? Once I get your okay I'll merge the branch into master

**Comment by bimmlerd** [comment]
Sorry, had a non-tech only analysis day yesterday. Will have a look at it.

**Comment by bimmlerd** [comment]
Improved the layout in 45419016b0bdfbd4307039412c4cabe4bbe69b32

**Comment by pennatil** [comment]
Is it ok to merge?

**Comment by bimmlerd** [comment]
Sure.

**Comment by pennatil** [comment]
All the missing content has been added in commit 15c9a3d289a09f400a273f580ea6a40bafe4e9d2
