### ISSUE TITLE
Chapter 7: Title

### ISSUE THREAD

**Issue by limenet** [pennatil/Analysis-Notes#68]
This one slipped my attention while proofing: Chapter 7's title should read "Gewöhnliche Differentialgleichungen" and not "Gewöhnliche Differenzialgleichungen" (note the **z**). I guess this also requires a build.sh update/PDF rebuild, that's why (my excuse this time :P) I refrain from doing it myself.

**Comment by bimmlerd** [comment]
:+1: 
On it.

**Comment by limenet** [comment]
Great, thanks

**Comment by bimmlerd** [comment]
Heh. Too early D:
I changed it all over the place except in the actual text. Smart. Changed in 0f2093767e9287161b1dda6ceb31bdc62b81a9c6

**Comment by limenet** [comment]
Oh crap, I know that feeling all too well.
